from __future__ import annotations

import os
import warnings
from typing import List, Tuple, Union
from flask import Flask, jsonify
from flask_cors import CORS
from app.core.config import API_PREFIX, CORS_ORIGINS, PERMANENT_SESSION_LIFETIME, SECRET_KEY, SESSION_COOKIE_NAME, SESSION_COOKIE_SAMESITE, SESSION_COOKIE_SECURE

def _parse_origins(origins_raw: str) -> Tuple[Union[str, List[str]], bool]:
    raw=(origins_raw or "").strip()
    if not raw or raw=="*": return "*",False
    return [origin.strip() for origin in raw.split(",") if origin.strip()],True

def create_app() -> Flask:
    app=Flask(__name__); secret_key=(SECRET_KEY or "").strip()
    if not secret_key:
        if os.getenv("FLASK_ENV")=="development": secret_key="dev-secret-key-do-not-use-in-production"; warnings.warn("Using temporary SECRET_KEY in development only")
        else: raise RuntimeError("SECRET_KEY environment variable is required in production")
    app.config.update(SECRET_KEY=secret_key,SESSION_COOKIE_NAME=SESSION_COOKIE_NAME,SESSION_COOKIE_HTTPONLY=True,SESSION_COOKIE_SECURE=SESSION_COOKIE_SECURE,SESSION_COOKIE_SAMESITE=SESSION_COOKIE_SAMESITE,SESSION_COOKIE_PATH="/",PERMANENT_SESSION_LIFETIME=PERMANENT_SESSION_LIFETIME)
    origins,supports_credentials=_parse_origins(CORS_ORIGINS); CORS(app,resources={r"/*":{"origins":origins}},supports_credentials=supports_credentials)
    from app.services.account_session_context import attach_verified_session_email_to_json
    app.before_request(attach_verified_session_email_to_json)
    from app.services.passport_index_provider_travelbuddy_patch import apply_patch
    apply_patch()
    from app.services.job_discovery_hardening import install as install_job_discovery_hardening
    from app.services.job_ats_extensions import install as install_job_ats_extensions
    from app.services.job_vacancy_identity import install as install_job_vacancy_identity
    install_job_discovery_hardening();install_job_ats_extensions();install_job_vacancy_identity()
    from app.routes import account,account_action_center,account_auth,account_controls,account_controls_admin,account_outcomes,admin,admin_review_evidence_extension,admin_review_queue,application_case_alerts,application_case_links,application_cases,application_cases_admin,billing,billing_admin,education_planner,evidence_admin,evidence_workflow,financial_readiness,health,journey_planner,job_application_analytics,job_application_drafts,job_application_followups,job_application_handoffs,job_application_lifecycle,job_application_portfolio,job_application_readiness,job_automation,job_career_practice,job_employers,job_recruiter_relationships,job_search_campaigns,jobs,language_coach,language_coach_extension,opportunities,opportunity_finder,operations,partners,passport_destination_detail,passport_official_source_admin,passport_provider,passport_provider_schedule,platform_modules,profiles,readiness_tools,relocation_public,reports,route_comparison,saved_route_reports,saved_routes,service_handoff_safety,service_handoffs,settlement_execution,smart_alerts,source_governance,timeline,travel_planner,visa_power,watchlist
    from app.routes.visa_power_safety import visa_power_check_safe
    from app.services.application_case_module_patch import apply_application_case_module_patch
    from app.services.job_alert_reconciliation import apply_job_alert_reconciliation
    from app.services.job_automation_postgrest_compat import apply_postgrest_zero_row_compat
    from app.services.job_automation_profile_patch import apply_job_automation_profile_patch
    from app.services.journey_module_patch import apply_journey_module_patch
    from app.services.platform_account_modules_patch import apply_platform_account_modules_patch
    from app.services.travel_provider_publication import apply_travel_provider_publication_patch
    apply_journey_module_patch();apply_application_case_module_patch();apply_travel_provider_publication_patch();apply_platform_account_modules_patch();apply_postgrest_zero_row_compat();apply_job_automation_profile_patch(job_automation)
    app.register_blueprint(health.bp);app.register_blueprint(relocation_public.bp,url_prefix=f"{API_PREFIX}/relocation");app.register_blueprint(platform_modules.bp,url_prefix=f"{API_PREFIX}/platform");app.register_blueprint(opportunities.bp,url_prefix=f"{API_PREFIX}/opportunities");app.register_blueprint(opportunity_finder.bp,url_prefix=f"{API_PREFIX}/opportunity-finder");app.register_blueprint(reports.bp,url_prefix=f"{API_PREFIX}/reports");app.register_blueprint(readiness_tools.bp,url_prefix=f"{API_PREFIX}/readiness");app.register_blueprint(financial_readiness.bp,url_prefix=f"{API_PREFIX}/financial-readiness");app.register_blueprint(route_comparison.bp,url_prefix=f"{API_PREFIX}/route-comparison");app.register_blueprint(evidence_workflow.bp,url_prefix=f"{API_PREFIX}/evidence")
    app.register_blueprint(application_cases.user_bp,url_prefix=f"{API_PREFIX}/applications");app.register_blueprint(application_case_alerts.user_bp,url_prefix=f"{API_PREFIX}/applications");app.register_blueprint(application_case_links.bp,url_prefix=f"{API_PREFIX}/applications");app.register_blueprint(journey_planner.bp,url_prefix=f"{API_PREFIX}/journey");app.register_blueprint(jobs.bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(job_automation.user_bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(job_application_readiness.bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(job_application_drafts.bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(job_application_handoffs.bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(job_application_lifecycle.bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(job_application_followups.bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(job_application_portfolio.bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(job_application_analytics.bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(job_career_practice.bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(job_search_campaigns.bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(job_employers.bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(job_recruiter_relationships.bp,url_prefix=f"{API_PREFIX}/jobs");app.register_blueprint(language_coach.bp,url_prefix=f"{API_PREFIX}/language-coach");app.register_blueprint(language_coach_extension.bp,url_prefix=f"{API_PREFIX}/language-coach");app.register_blueprint(education_planner.bp,url_prefix=f"{API_PREFIX}/education");app.register_blueprint(travel_planner.bp,url_prefix=f"{API_PREFIX}/travel");app.register_blueprint(billing.bp,url_prefix=f"{API_PREFIX}/billing");app.register_blueprint(operations.public_bp,url_prefix=f"{API_PREFIX}/operations");app.register_blueprint(source_governance.public_bp,url_prefix=f"{API_PREFIX}/source-health");app.register_blueprint(watchlist.bp,url_prefix=f"{API_PREFIX}/watchlist");app.register_blueprint(saved_routes.bp,url_prefix=f"{API_PREFIX}/saved-routes");app.register_blueprint(saved_route_reports.bp,url_prefix=f"{API_PREFIX}/saved-route-reports");app.register_blueprint(timeline.bp,url_prefix=f"{API_PREFIX}/timeline");app.register_blueprint(partners.bp,url_prefix=f"{API_PREFIX}/partners");app.register_blueprint(profiles.bp,url_prefix=f"{API_PREFIX}/profiles");app.register_blueprint(account_auth.bp,url_prefix=f"{API_PREFIX}/auth");app.register_blueprint(account.bp,url_prefix=f"{API_PREFIX}/account");app.register_blueprint(account_controls.bp,url_prefix=f"{API_PREFIX}/account");app.register_blueprint(account_action_center.bp,url_prefix=f"{API_PREFIX}/account");app.register_blueprint(account_outcomes.bp,url_prefix=f"{API_PREFIX}/account");app.register_blueprint(smart_alerts.bp,url_prefix=f"{API_PREFIX}/account")
    app.register_blueprint(service_handoffs.user_bp,url_prefix=f"{API_PREFIX}/handoffs");app.register_blueprint(service_handoffs.user_bp,url_prefix=f"{API_PREFIX}/service-handoffs",name="service_handoffs_alias");app.register_blueprint(passport_provider.bp,url_prefix=f"{API_PREFIX}/visa-power");app.register_blueprint(passport_provider_schedule.bp,url_prefix=f"{API_PREFIX}/visa-power");app.register_blueprint(passport_destination_detail.bp,url_prefix=f"{API_PREFIX}/visa-power");app.register_blueprint(visa_power.bp,url_prefix=f"{API_PREFIX}/visa-power");app.register_blueprint(platform_modules.planned_bp,url_prefix=API_PREFIX)
    app.register_blueprint(admin.bp,url_prefix=f"{API_PREFIX}/admin");app.register_blueprint(admin_review_queue.bp,url_prefix=f"{API_PREFIX}/admin");app.register_blueprint(application_cases_admin.bp,url_prefix=f"{API_PREFIX}/admin");app.register_blueprint(application_case_alerts.admin_bp,url_prefix=f"{API_PREFIX}/admin");app.register_blueprint(job_automation.admin_bp,url_prefix=f"{API_PREFIX}/admin");app.register_blueprint(account_controls_admin.bp,url_prefix=f"{API_PREFIX}/admin");app.register_blueprint(billing_admin.bp,url_prefix=f"{API_PREFIX}/admin");app.register_blueprint(evidence_admin.bp,url_prefix=f"{API_PREFIX}/admin");app.register_blueprint(service_handoffs.admin_bp,url_prefix=f"{API_PREFIX}/admin");app.register_blueprint(source_governance.admin_bp,url_prefix=f"{API_PREFIX}/admin");app.register_blueprint(operations.admin_bp,url_prefix=f"{API_PREFIX}/admin");app.register_blueprint(passport_official_source_admin.bp,url_prefix=f"{API_PREFIX}/admin")
    apply_job_alert_reconciliation(app)
    app.view_functions["passport_provider.visa_power_check_live"]=visa_power_check_safe;app.view_functions["service_handoffs_admin.update_handoff_status"]=service_handoff_safety.safe_update_handoff_status;app.view_functions["service_handoffs_admin.update_support_case"]=service_handoff_safety.safe_update_support_case;app.view_functions["admin_review_queue.review_queue"]=admin_review_evidence_extension.review_queue_with_evidence;app.view_functions["journey_planner.settlement_plan"]=settlement_execution.settlement_plan_with_timeline
    @app.get("/")
    def root(): return jsonify({"ok":True,"service":"MoveReady API","api_prefix":API_PREFIX})
    return app