-- Project MoveReady MVP
-- Official ballots, visa lotteries, invitation pools, and quota opportunities.
-- Run after 001, 002, 003, and 004 migrations.

create table if not exists public.relocation_opportunities (
  id uuid primary key default gen_random_uuid(),
  opportunity_code text not null unique,
  country_code text not null,
  country_name text not null,
  opportunity_name text not null,
  opportunity_type text not null check (opportunity_type in ('lottery', 'ballot', 'invitation_pool', 'annual_quota', 'country_cap', 'first_come_quota', 'seasonal_intake')),
  route_category text not null default 'opportunity',
  availability_status text not null default 'monitoring' check (availability_status in ('open', 'closed', 'monitoring', 'results_open', 'paused', 'unknown')),
  official_url text not null,
  result_check_url text,
  summary text not null,
  eligibility_summary text,
  application_window_summary text,
  safety_notes text,
  registration_opens_at timestamptz,
  registration_closes_at timestamptz,
  result_check_opens_at timestamptz,
  result_check_closes_at timestamptz,
  source_confidence text not null default 'high' check (source_confidence in ('high', 'medium', 'low')),
  last_verified_at timestamptz,
  next_review_due_at timestamptz,
  tags text[] not null default '{}',
  metadata jsonb not null default '{}',
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists relocation_opportunities_country_idx on public.relocation_opportunities (country_code, availability_status);
create index if not exists relocation_opportunities_type_idx on public.relocation_opportunities (opportunity_type, availability_status);
create index if not exists relocation_opportunities_public_idx on public.relocation_opportunities (is_public, updated_at desc);
create index if not exists relocation_opportunities_tags_idx on public.relocation_opportunities using gin (tags);

drop trigger if exists trg_relocation_opportunities_updated_at on public.relocation_opportunities;
create trigger trg_relocation_opportunities_updated_at
before update on public.relocation_opportunities
for each row execute function public.relocation_set_updated_at();

insert into public.relocation_opportunities (
  opportunity_code,
  country_code,
  country_name,
  opportunity_name,
  opportunity_type,
  availability_status,
  official_url,
  result_check_url,
  summary,
  eligibility_summary,
  application_window_summary,
  safety_notes,
  source_confidence,
  last_verified_at,
  next_review_due_at,
  tags,
  metadata
)
values
(
  'US-DV',
  'US',
  'United States',
  'Diversity Visa Program',
  'lottery',
  'monitoring',
  'https://travel.state.gov/content/travel/en/us-visas/immigrate/diversity-visa-program-entry.html',
  'https://dvprogram.state.gov/',
  'Annual diversity immigrant visa route for people from eligible countries with historically low immigration to the United States.',
  'Eligibility depends on country rules plus education or work-experience requirements published by the U.S. Department of State.',
  'Entries are accepted only during the official registration period. DV-2027 start date is to be announced by the Department of State.',
  'Use only the official E-DV website. Do not submit duplicate entries. No one can guarantee selection.',
  'high',
  now(),
  now() + interval '14 days',
  array['usa', 'diversity visa', 'green card', 'lottery', 'official-only'],
  '{"source_note":"Official U.S. Department of State DV entry guidance."}'::jsonb
),
(
  'CA-IEC',
  'CA',
  'Canada',
  'International Experience Canada invitation pools',
  'invitation_pool',
  'open',
  'https://ircc.canada.ca/english/work/iec/selections.asp',
  null,
  'Invitation-pool system for eligible youth from partner countries and territories to work and travel in Canada.',
  'Eligibility depends on citizenship/territory, age, category, quota, admissibility, and whether a profile can be created for the season.',
  'The 2026 IEC season is open. Country-specific spots, invitation chances, and dates are updated by IRCC.',
  'Selection is not guaranteed. Users must follow official IRCC instructions and deadlines after invitation.',
  'high',
  now(),
  now() + interval '7 days',
  array['canada', 'iec', 'working holiday', 'invitation pool', 'youth mobility'],
  '{"source_note":"Official IRCC rounds of invitations page."}'::jsonb
),
(
  'AU-462-BALLOT',
  'AU',
  'Australia',
  'Work and Holiday subclass 462 ballot and country caps',
  'ballot',
  'monitoring',
  'https://immi.homeaffairs.gov.au/what-we-do/whm-program/status-of-country-caps',
  null,
  'Work and Holiday route with annual caps for some countries and ballot/pre-application process for selected high-demand partner countries.',
  'Eligibility depends on passport country, age, education, funds, health, character, and country-specific subclass 462 rules.',
  'Program year runs from 1 July to 30 June. Country caps and ballot arrangements should be checked on Home Affairs before applying.',
  'Ballot selection only allows a person to apply. It does not guarantee visa grant.',
  'high',
  now(),
  now() + interval '14 days',
  array['australia', 'subclass 462', 'work and holiday', 'ballot', 'country cap'],
  '{"source_note":"Official Australian Home Affairs WHM country-cap and ballot information."}'::jsonb
),
(
  'UK-IYPS',
  'GB',
  'United Kingdom',
  'India Young Professionals Scheme ballot',
  'ballot',
  'monitoring',
  'https://www.gov.uk/guidance/india-young-professionals-scheme-visa-ballot-system',
  null,
  'Ballot route for eligible Indian citizens who want to apply under the India Young Professionals Scheme visa.',
  'Eligibility includes Indian citizenship, age rules, qualification and savings requirements, and selection in the ballot before application.',
  'Ballot dates and entry instructions are published by GOV.UK and must be checked before each opening.',
  'Entering a ballot is not approval. Use only official GOV.UK guidance and do not pay anyone promising selection.',
  'high',
  now(),
  now() + interval '14 days',
  array['uk', 'india', 'young professionals', 'youth mobility', 'ballot'],
  '{"source_note":"Official GOV.UK India Young Professionals Scheme ballot guidance."}'::jsonb
),
(
  'NZ-PAC',
  'NZ',
  'New Zealand',
  'Pacific Access Category ballot',
  'annual_quota',
  'closed',
  'https://www.immigration.govt.nz/formshelp/pac-sq-registration',
  'https://www.immigration.govt.nz/live/resident-visas-to-live-in-new-zealand/resident-visas-for-samoa-kiribati-tuvalu-tonga-and-fiji-nationals/pacific-access-category-resident-visa-ballot-results/',
  'Annual ballot route for eligible citizens of selected Pacific countries to apply for New Zealand residence if drawn.',
  'Eligibility is limited to specified Pacific nationalities and official Immigration New Zealand rules.',
  'The 2026 ballot has closed. Immigration New Zealand indicates registrations can reopen in 2027 with dates to be announced.',
  'A drawn ballot registration is an invitation step, not automatic residence. Check official INZ instructions before paying anyone.',
  'high',
  now(),
  now() + interval '30 days',
  array['new zealand', 'pacific access', 'ballot', 'quota', 'residence'],
  '{"source_note":"Official Immigration New Zealand PAC and SQ registration and results pages."}'::jsonb
),
(
  'NZ-SQ',
  'NZ',
  'New Zealand',
  'Samoan Quota Resident Visa ballot',
  'annual_quota',
  'closed',
  'https://www.immigration.govt.nz/formshelp/pac-sq-registration',
  'https://www.immigration.govt.nz/live/resident-visas-to-live-in-new-zealand/resident-visas-for-samoa-kiribati-tuvalu-tonga-and-fiji-nationals/samoan-quota-resident-visa-ballot-results/',
  'Annual quota ballot allowing selected Samoan citizens to apply for New Zealand residence.',
  'Eligibility is limited to Samoan citizens who meet official ballot and resident visa requirements.',
  'The 2026 ballot has closed. Future opening dates should be verified directly from Immigration New Zealand.',
  'A ballot draw is not final approval. Users should keep their registration number and follow official INZ instructions.',
  'high',
  now(),
  now() + interval '30 days',
  array['new zealand', 'samoa', 'samoan quota', 'ballot', 'residence'],
  '{"source_note":"Official Immigration New Zealand SQ registration and results pages."}'::jsonb
),
(
  'HK-WHS',
  'HK',
  'Hong Kong',
  'Working Holiday Scheme quotas',
  'first_come_quota',
  'monitoring',
  'https://www.immd.gov.hk/eng/services/visas/working_holiday_scheme.html',
  null,
  'Working Holiday Scheme with eligibility and quota rules for partner economies.',
  'Eligibility depends on nationality/partner economy, age, funds, insurance and other Hong Kong Immigration Department criteria.',
  'Quota and application details must be checked on the official Immigration Department page for the relevant partner economy.',
  'This is not permanent relocation. Check employment, study and dependent restrictions before applying.',
  'high',
  now(),
  now() + interval '30 days',
  array['hong kong', 'working holiday', 'quota', 'youth mobility'],
  '{"source_note":"Official Hong Kong Immigration Department Working Holiday Scheme page."}'::jsonb
),
(
  'JP-WH',
  'JP',
  'Japan',
  'Working Holiday Programmes in Japan',
  'annual_quota',
  'monitoring',
  'https://www.mofa.go.jp/j_info/visit/w_holiday/index.html',
  null,
  'Working holiday programmes for eligible youth from Japan partner countries and regions.',
  'Eligibility depends on citizenship/region, age, funds, travel purpose and country-specific embassy or consular rules.',
  'Japan MOFA lists partner countries/regions and maximum numbers where applicable. Applicants should check their local Japanese mission.',
  'This route is for holiday and cultural exchange with incidental work; it should not be presented as a guaranteed job route.',
  'high',
  now(),
  now() + interval '30 days',
  array['japan', 'working holiday', 'quota', 'youth mobility'],
  '{"source_note":"Official Ministry of Foreign Affairs of Japan Working Holiday Programmes page."}'::jsonb
)
on conflict (opportunity_code) do update set
  country_code = excluded.country_code,
  country_name = excluded.country_name,
  opportunity_name = excluded.opportunity_name,
  opportunity_type = excluded.opportunity_type,
  availability_status = excluded.availability_status,
  official_url = excluded.official_url,
  result_check_url = excluded.result_check_url,
  summary = excluded.summary,
  eligibility_summary = excluded.eligibility_summary,
  application_window_summary = excluded.application_window_summary,
  safety_notes = excluded.safety_notes,
  source_confidence = excluded.source_confidence,
  last_verified_at = excluded.last_verified_at,
  next_review_due_at = excluded.next_review_due_at,
  tags = excluded.tags,
  metadata = excluded.metadata,
  is_public = true,
  updated_at = now();
