-- MoveReady Language Coach V1 starter practice bank
-- All questions below are original MoveReady exam-style content, not recalled/live exam material.

insert into relocation_language_questions (language, exam, skill, difficulty, prompt, choices, correct_answer, explanation, content_origin)
values
('english','IELTS General','grammar',1,'Choose the sentence that is grammatically correct.','["She has worked here for three years.","She work here since three years.","She is work here for three years.","She working here since three years."]','She has worked here for three years.','Use the present perfect for an action that began in the past and continues to the present.','moveready_original'),
('english','IELTS General','vocabulary',1,'In a workplace notice, what does “mandatory” most nearly mean?','["Optional","Required","Delayed","Expensive"]','Required','Mandatory means required or compulsory.','moveready_original'),
('english','IELTS General','reading',2,'Notice: The staff entrance will be closed from 6 p.m. Friday until 7 a.m. Monday for maintenance. Employees working during this period should use the east entrance. Which entrance should a Saturday employee use?','["Staff entrance","East entrance","Main visitor entrance","Loading entrance"]','East entrance','The notice directly instructs employees working during the closure to use the east entrance.','moveready_original'),
('english','IELTS General','grammar',2,'Complete the sentence: If the documents arrive today, we ___ the application tomorrow.','["submit","submitted","will submit","would submitted"]','will submit','A real future condition commonly uses present simple in the if-clause and will + verb in the result clause.','moveready_original'),
('english','IELTS General','vocabulary',2,'Which word best completes the sentence? The employer asked for a ___ copy of the certificate, not the original.','["duplicate","temporary","vacant","remote"]','duplicate','A duplicate is an additional copy of an original document.','moveready_original'),
('english','IELTS General','reading',3,'Email: Your interview remains scheduled for 10:00 a.m. on Tuesday. Please arrive 15 minutes early for security registration. Candidates arriving after 10:00 may need to reschedule. What is the best arrival time?','["9:45 a.m.","10:00 a.m.","10:15 a.m.","9:15 a.m."]','9:45 a.m.','Arriving 15 minutes before a 10:00 a.m. interview means 9:45 a.m.','moveready_original'),
('english','IELTS General','grammar',3,'Choose the best completion: The manager recommended that the applicant ___ the updated form.','["submits","submit","submitted","submitting"]','submit','After recommend that, formal English commonly uses the base-form subjunctive: submit.','moveready_original'),
('english','IELTS General','vocabulary',3,'In immigration planning, a “deadline” is best described as:','["a recommended destination","the latest time something must be completed","a financial deposit","a type of interview"]','the latest time something must be completed','A deadline is the final/latest time by which an action must be completed.','moveready_original'),
('french','TEF Canada','vocabulary',1,'Choisissez le mot qui complète la phrase : Je dois ___ mon passeport avant le voyage.','["renouveler","fermer","oublier","vendre"]','renouveler','On renouvelle un passeport lorsqu’il arrive à expiration.','moveready_original'),
('french','TEF Canada','grammar',1,'Choisissez la phrase correcte.','["Nous habitons ici depuis deux ans.","Nous habitons ici il y a deux ans.","Nous habite ici depuis deux ans.","Nous habitons ici pour deux ans passé."]','Nous habitons ici depuis deux ans.','Depuis s’emploie avec le présent pour une situation commencée dans le passé et toujours vraie.','moveready_original'),
('french','TEF Canada','reading',2,'Avis : Le bureau sera fermé mercredi matin. Il ouvrira à 13 h. À quelle heure peut-on venir mercredi ?','["9 h","11 h","13 h 30","12 h"]','13 h 30','Le bureau ouvre à 13 h ; 13 h 30 est donc une heure possible.','moveready_original'),
('french','TEF Canada','vocabulary',2,'Dans une offre d’emploi, “expérience exigée” signifie :','["expérience facultative","expérience obligatoire","formation gratuite","travail à distance"]','expérience obligatoire','Exigée signifie demandée comme condition obligatoire.','moveready_original'),
('french','TEF Canada','grammar',2,'Complétez : Si j’obtiens le visa, je ___ au Canada en septembre.','["partirai","partais","partir","parti"]','partirai','Pour une condition réelle au futur : si + présent, puis futur simple.','moveready_original'),
('french','TEF Canada','reading',3,'Message : Votre rendez-vous est à 14 h. Merci de vous présenter vingt minutes avant avec une pièce d’identité. À quelle heure faut-il arriver ?','["13 h 20","13 h 40","14 h","14 h 20"]','13 h 40','Vingt minutes avant 14 h correspond à 13 h 40.','moveready_original'),
('french','TEF Canada','grammar',3,'Choisissez la bonne réponse : Il faut que vous ___ ce formulaire avant vendredi.','["remplissez","remplissiez","remplir","rempli"]','remplissiez','Après “il faut que”, on emploie le subjonctif : que vous remplissiez.','moveready_original'),
('french','TEF Canada','vocabulary',3,'Le mot “échéance” désigne le plus souvent :','["une date limite","un logement","un entretien","un diplôme"]','une date limite','Une échéance est une date ou limite prévue pour accomplir une obligation.','moveready_original');
