-- Project MoveReady MVP
-- Working holiday and youth mobility opportunity seed data.
-- Run after the relocation_opportunities table migration.
-- Safe to rerun.

insert into public.relocation_opportunities (
  opportunity_code,
  country_code,
  country_name,
  opportunity_name,
  opportunity_type,
  route_category,
  availability_status,
  official_url,
  result_check_url,
  summary,
  eligibility_summary,
  application_window_summary,
  safety_notes,
  source_confidence,
  last_verified_at,
  next_review_due_at,
  tags,
  is_public
)
values
  (
    'JP-WH',
    'JP',
    'Japan',
    'Working Holiday Programme',
    'annual_quota',
    'working_holiday',
    'monitoring',
    'https://www.mofa.go.jp/j_info/visit/w_holiday/index.html',
    null,
    'Partner-country working holiday route for eligible young people who want an extended holiday in Japan with incidental work rights.',
    'Eligibility depends on nationality, age, quota, funds, health, character, and embassy-specific instructions for the applicant country.',
    'Opening windows and quota handling vary by partner country and Japanese mission. Users should verify the current embassy instruction before applying.',
    'This is a holiday-first route and should not be treated as a guaranteed employment, skilled work, or permanent migration pathway.',
    'high',
    now(),
    now() + interval '30 days',
    array['japan', 'working holiday', 'youth mobility', 'annual quota', 'embassy'],
    true
  ),
  (
    'KR-WH',
    'KR',
    'South Korea',
    'Working Holiday Visa',
    'annual_quota',
    'working_holiday',
    'monitoring',
    'https://whic.mofa.go.kr/contents.do?contentsNo=38&menuNo=90',
    null,
    'Working holiday route for eligible young people from Korea partner countries who want a temporary holiday stay with limited work rights.',
    'Eligibility depends on nationality, age, quota, funds, insurance, purpose of stay, and Korean mission instructions.',
    'Quota and intake handling vary by country agreement and consular process. Users should verify the current national quota and application channel.',
    'This route is not a dependant, permanent migration, or guaranteed employment route. Users must follow country-specific working holiday conditions.',
    'high',
    now(),
    now() + interval '30 days',
    array['korea', 'south korea', 'working holiday', 'youth mobility', 'quota'],
    true
  ),
  (
    'HK-WHS',
    'HK',
    'Hong Kong',
    'Working Holiday Scheme',
    'first_come_quota',
    'working_holiday',
    'monitoring',
    'https://www.immd.gov.hk/eng/services/visas/working_holiday_scheme.html',
    null,
    'Working Holiday Scheme for eligible nationals of participating countries, with annual quotas and first-come quota pressure for some routes.',
    'Eligibility depends on participating nationality, age, financial means, insurance, travel purpose, and Immigration Department requirements.',
    'Annual country quotas and availability should be checked directly from the Hong Kong Immigration Department before applying.',
    'Temporary work and short study must stay within scheme conditions. Users should not assume dependants or repeat use are available.',
    'high',
    now(),
    now() + interval '30 days',
    array['hong kong', 'working holiday', 'annual quota', 'first come', 'youth mobility'],
    true
  ),
  (
    'IE-WHA',
    'IE',
    'Ireland',
    'Working Holiday Authorisation',
    'annual_quota',
    'working_holiday',
    'monitoring',
    'https://www.ireland.ie/en/usa/washington/services/visas/working-holiday-authorisation/',
    null,
    'Country-specific working holiday authorisation route for eligible young people from Ireland partner countries.',
    'Eligibility, age, fees, validity, permitted work, and application channel vary by citizenship and Irish mission location.',
    'Users should verify the Ireland.ie page for their citizenship and local Irish mission before relying on availability or timing.',
    'A working holiday authorisation should not be confused with ordinary visitor status or a guaranteed right to long-term residence.',
    'high',
    now(),
    now() + interval '30 days',
    array['ireland', 'working holiday', 'authorisation', 'youth mobility', 'country specific'],
    true
  )
on conflict (opportunity_code) do update set
  country_code = excluded.country_code,
  country_name = excluded.country_name,
  opportunity_name = excluded.opportunity_name,
  opportunity_type = excluded.opportunity_type,
  route_category = excluded.route_category,
  availability_status = excluded.availability_status,
  official_url = excluded.official_url,
  result_check_url = excluded.result_check_url,
  summary = excluded.summary,
  eligibility_summary = excluded.eligibility_summary,
  application_window_summary = excluded.application_window_summary,
  safety_notes = excluded.safety_notes,
  source_confidence = excluded.source_confidence,
  last_verified_at = excluded.last_verified_at,
  next_review_due_at = excluded.next_review_due_at,
  tags = excluded.tags,
  is_public = excluded.is_public,
  updated_at = now();
