from __future__ import annotations

import os


def env(name: str, default: str = "") -> str:
    return (os.getenv(name, default) or "").strip()


def env_any(*names: str, default: str = "") -> str:
    for name in names:
        value = env(name)
        if value:
            return value
    return default


def env_bool(name: str, default: bool = False) -> bool:
    value = env(name, "1" if default else "0").lower()
    return value in {"1", "true", "yes", "y", "on"}


def env_bool_any(*names: str, default: bool = False) -> bool:
    for name in names:
        value = env(name)
        if value:
            return value.lower() in {"1", "true", "yes", "y", "on"}
    return default


def env_int(name: str, default: int) -> int:
    try:
        return int(env(name, str(default)) or str(default))
    except Exception:
        return default


ENV_MODE = env("ENV_MODE", env("ENV", "development"))
FLASK_ENV = env("FLASK_ENV", "development")
PORT = env_int("PORT", 8000)
SECRET_KEY = env("SECRET_KEY")

API_PREFIX = env("API_PREFIX", "/api")
if API_PREFIX and not API_PREFIX.startswith("/"):
    API_PREFIX = "/" + API_PREFIX
API_PREFIX = API_PREFIX.rstrip("/") or "/api"

CORS_ORIGINS = env("CORS_ORIGINS", "http://localhost:3000")

SUPABASE_URL = env("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = env("SUPABASE_SERVICE_ROLE_KEY") or env("SUPABASE_SERVICE_KEY")

OPENAI_API_KEY = env("OPENAI_API_KEY")
OPENAI_MODEL = env("OPENAI_MODEL", "gpt-4o-mini")

ADMIN_API_KEY = (
    env("MOVEREADY_ADMIN_API_KEY")
    or env("MOVEREADY_ADMIN_KEY")
    or env("MOVE_READY_ADMIN_API_KEY")
    or env("ADMIN_API_KEY")
)

SESSION_COOKIE_NAME = env("SESSION_COOKIE_NAME", "moveready_session")
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", FLASK_ENV != "development")
SESSION_COOKIE_SAMESITE = env("SESSION_COOKIE_SAMESITE", "Lax")
PERMANENT_SESSION_LIFETIME = env_int("PERMANENT_SESSION_LIFETIME", 2592000)

AUTH_OTP_EXPIRES_MINUTES = max(3, min(30, env_int("AUTH_OTP_EXPIRES_MINUTES", 10)))
AUTH_MAX_CODE_ATTEMPTS = max(3, min(10, env_int("AUTH_MAX_CODE_ATTEMPTS", 5)))
AUTH_SESSION_DAYS = max(1, min(90, env_int("AUTH_SESSION_DAYS", 30)))
AUTH_MAX_ACTIVE_SESSIONS_PER_EMAIL = max(1, min(25, env_int("AUTH_MAX_ACTIVE_SESSIONS_PER_EMAIL", 10)))
AUTH_OTP_DEV_MODE = env_bool("AUTH_OTP_DEV_MODE", False)
AUTH_OTP_REQUEST_COOLDOWN_SECONDS = max(15, min(900, env_int("AUTH_OTP_REQUEST_COOLDOWN_SECONDS", 60)))
AUTH_OTP_REQUEST_WINDOW_MINUTES = max(1, min(1440, env_int("AUTH_OTP_REQUEST_WINDOW_MINUTES", 15)))
AUTH_OTP_MAX_REQUESTS_PER_EMAIL_WINDOW = max(1, min(25, env_int("AUTH_OTP_MAX_REQUESTS_PER_EMAIL_WINDOW", 5)))
AUTH_OTP_MAX_REQUESTS_PER_IP_WINDOW = max(1, min(100, env_int("AUTH_OTP_MAX_REQUESTS_PER_IP_WINDOW", 20)))
AUTH_OTP_RECENT_SCAN_LIMIT = max(50, min(1000, env_int("AUTH_OTP_RECENT_SCAN_LIMIT", 300)))
EMAIL_OTP_DELIVERY_ENABLED = env_bool("EMAIL_OTP_DELIVERY_ENABLED", False)

PLATFORM_MODULES_ENABLED = env_bool("PLATFORM_MODULES_ENABLED", True)
OPPORTUNITY_ALERTS_ENABLED = env_bool("OPPORTUNITY_ALERTS_ENABLED", False)
WHATSAPP_ALERTS_ENABLED = env_bool("WHATSAPP_ALERTS_ENABLED", False)
VISA_POWER_ENABLED = env_bool("VISA_POWER_ENABLED", True)
COMMERCIAL_QUOTES_ENABLED = env_bool("COMMERCIAL_QUOTES_ENABLED", True)
PAYMENT_LINKS_ENABLED = env_bool("PAYMENT_LINKS_ENABLED", False)

PASSPORT_INDEX_PROVIDER_ENABLED = env_bool_any("PASSPORT_INDEX_PROVIDER_ENABLED", "RAPIDAPI_ENABLED", default=False)
PASSPORT_INDEX_PROVIDER_NAME = env_any("PASSPORT_INDEX_PROVIDER_NAME", "RAPIDAPI_PROVIDER_NAME", default="MoveReady starter cache")
PASSPORT_INDEX_PROVIDER_URL = env_any("PASSPORT_INDEX_PROVIDER_URL", "RAPIDAPI_URL", "RAPIDAPI_ENDPOINT", "VISA_REQUIREMENT_API_URL")
PASSPORT_INDEX_PROVIDER_KEY = env_any("PASSPORT_INDEX_PROVIDER_KEY", "RAPIDAPI_KEY", "X_RAPIDAPI_KEY", "RAPID_API_KEY")
PASSPORT_INDEX_PROVIDER_METHOD = env_any("PASSPORT_INDEX_PROVIDER_METHOD", "RAPIDAPI_METHOD", default="GET").upper()
PASSPORT_INDEX_PROVIDER_AUTH_HEADER = env_any("PASSPORT_INDEX_PROVIDER_AUTH_HEADER", "RAPIDAPI_AUTH_HEADER", default="X-API-Key")
PASSPORT_INDEX_PROVIDER_HOST_HEADER = env_any("PASSPORT_INDEX_PROVIDER_HOST_HEADER", "RAPIDAPI_HOST", "X_RAPIDAPI_HOST")
PASSPORT_INDEX_PROVIDER_EXTRA_HEADERS_JSON = env("PASSPORT_INDEX_PROVIDER_EXTRA_HEADERS_JSON", "{}")
PASSPORT_INDEX_PROVIDER_COUNTRY_CODE_FORMAT = env_any("PASSPORT_INDEX_PROVIDER_COUNTRY_CODE_FORMAT", "RAPIDAPI_COUNTRY_CODE_FORMAT", default="alpha2").lower()
PASSPORT_INDEX_PROVIDER_TIMEOUT_SECONDS = env_int("PASSPORT_INDEX_PROVIDER_TIMEOUT_SECONDS", 20)
PASSPORT_INDEX_CACHE_MAX_DAYS = env_int("PASSPORT_INDEX_CACHE_MAX_DAYS", 7)
PASSPORT_INDEX_SYNC_WEEKDAYS = env("PASSPORT_INDEX_SYNC_WEEKDAYS", "FRI")
PASSPORT_INDEX_SYNC_HOUR_UTC = min(23, max(0, env_int("PASSPORT_INDEX_SYNC_HOUR_UTC", 6)))
PASSPORT_INDEX_SYNC_MINUTE_UTC = min(59, max(0, env_int("PASSPORT_INDEX_SYNC_MINUTE_UTC", 17)))
PASSPORT_INDEX_SCHEDULED_COUNTRIES = env("PASSPORT_INDEX_SCHEDULED_COUNTRIES", "Nigeria")
PASSPORT_INDEX_MAX_COUNTRIES_PER_SYNC = max(1, env_int("PASSPORT_INDEX_MAX_COUNTRIES_PER_SYNC", 1))

DOCUMENT_CHECKS_ENABLED = env_bool("DOCUMENT_CHECKS_ENABLED", False)
PROOF_OF_FUNDS_PLANNER_ENABLED = env_bool("PROOF_OF_FUNDS_PLANNER_ENABLED", False)
REFUSAL_ANALYZER_ENABLED = env_bool("REFUSAL_ANALYZER_ENABLED", False)
LEGALIZATION_MODULE_ENABLED = env_bool("LEGALIZATION_MODULE_ENABLED", False)
COURIER_MODULE_ENABLED = env_bool("COURIER_MODULE_ENABLED", False)
INSURANCE_PARTNER_ENABLED = env_bool("INSURANCE_PARTNER_ENABLED", False)
APPOINTMENT_TRACKER_ENABLED = env_bool("APPOINTMENT_TRACKER_ENABLED", False)
FAMILY_PLANNER_ENABLED = env_bool("FAMILY_PLANNER_ENABLED", False)
SETTLEMENT_MODULE_ENABLED = env_bool("SETTLEMENT_MODULE_ENABLED", False)
PARTNER_MARKETPLACE_ENABLED = env_bool("PARTNER_MARKETPLACE_ENABLED", False)
